heat_template_version: 2013-05-23

description: |
  This is a Heat template to deploy a single Linux server running elasticsearch.

parameters:

  image:
    label: Server Image
    description: Operating system to use for your server.
    type: string
    default: Debian 7 (Wheezy) (PVHVM) 

  flavor:
    description: Flavor for Cloud Servers
    type: string
    default: 2 GB General Purpose v1

  server_hostname:
    description: Hostname for the server.
    type: string
    default: POC-minion%index%

  ssh_keypair_name:
    description: Nova keypair name for ssh access to the server
    type: string

  salt_network: 
    description: salt network 
    type: string

  ssh_private_key:
    description: private key to access the created servers
    type: string

  stack_id:
    description: Stack ID
    type: string

resources:
  salt_minion_server:
    type: 'Rackspace::Cloud::Server'
    properties:
      flavor:
          get_param: flavor
      name: salt-minion%index%
      key_name:
          get_resource: ssh_key
      image:
          get_param: image
      user_data:
          str_replace:
              params:
                  '%salt_master%':
                      get_attr:
                          - salt_master_server
                          - networks
                          - salt_network
                          - 0
              template: "#!/bin/bash\napt-get update\napt-get install python-software-properties -y\nadd-apt-repository ppa:saltstack/salt -y\napt-get update\napt-get install salt-minion -y\nsed -i 's/^#master: salt$/master: %salt_master%/' /etc/salt/minion\n/etc/init.d/salt-minion restart\n"
      networks:
          -
              uuid: 00000000-0000-0000-0000-000000000000
          -
              uuid: 11111111-1111-1111-1111-111111111111
          -
              uuid:
                  get_resource: salt_network
  es_server:
    type: "Rackspace::Cloud::Server"
    properties:
      name: { get_param: server_hostname }
      flavor: { get_param: flavor }
      image: { get_param: image }
      key_name: { get_param: ssh_keypair_name }
      metadata:
        rax-heat: { get_param: "stack_id" }
      networks:
      - uuid: "00000000-0000-0000-0000-000000000000"
      - uuid: "11111111-1111-1111-1111-111111111111"
      - uuid: { get_param: es_network_id }

  encrypted_volume:
    type: OS::Cinder::Volume
    properties:
      name: encrypted_volume
      metadata:
        rax-heat: { get_param: "OS::stack_id" }
      size: 75
      description: Created from the kitchen_sink test Heat template

  attach_devops_vol:
    type: OS::Cinder::VolumeAttachment
    properties:
      instance_uuid: { get_resource: salt_minion_server }
      volume_id: { get_resource: encrypted_volume }

